// Code generated by help.awk. DO NOT EDIT.
// GENERATED FILE DO NOT EDIT

package parser

var helpMessages = map[string]HelpMessageBody{
	//line sql.y: 1152
	`ALTER`: {
		//line sql.y: 1153
		Category: hGroup,
		//line sql.y: 1154
		Text: `ALTER TABLE, ALTER INDEX, ALTER VIEW, ALTER SEQUENCE, ALTER DATABASE, ALTER USER, ALTER ROLE
`,
	},
	//line sql.y: 1169
	`ALTER TABLE`: {
		ShortDescription: `change the definition of a table`,
		//line sql.y: 1170
		Category: hDDL,
		//line sql.y: 1171
		Text: `
ALTER TABLE [IF EXISTS] <tablename> <command> [, ...]

Commands:
  ALTER TABLE ... ADD [COLUMN] [IF NOT EXISTS] <colname> <type> [<qualifiers...>]
  ALTER TABLE ... ADD <constraint>
  ALTER TABLE ... DROP [COLUMN] [IF EXISTS] <colname> [RESTRICT | CASCADE]
  ALTER TABLE ... DROP CONSTRAINT [IF EXISTS] <constraintname> [RESTRICT | CASCADE]
  ALTER TABLE ... ALTER [COLUMN] <colname> {SET DEFAULT <expr> | DROP DEFAULT}
  ALTER TABLE ... ALTER [COLUMN] <colname> DROP NOT NULL
  ALTER TABLE ... ALTER [COLUMN] <colname> DROP STORED
  ALTER TABLE ... ALTER [COLUMN] <colname> [SET DATA] TYPE <type> [COLLATE <collation>]
  ALTER TABLE ... ALTER PRIMARY KEY USING INDEX <name>
  ALTER TABLE ... RENAME TO <newname>
  ALTER TABLE ... RENAME [COLUMN] <colname> TO <newname>
  ALTER TABLE ... VALIDATE CONSTRAINT <constraintname>
  ALTER TABLE ... SPLIT AT <selectclause> [WITH EXPIRATION <expr>]
  ALTER TABLE ... UNSPLIT AT <selectclause>
  ALTER TABLE ... UNSPLIT ALL
  ALTER TABLE ... SCATTER [ FROM ( <exprs...> ) TO ( <exprs...> ) ]
  ALTER TABLE ... INJECT STATISTICS ...  (experimental)
  ALTER TABLE ... PARTITION BY RANGE ( <name...> ) ( <rangespec> )
  ALTER TABLE ... PARTITION BY LIST ( <name...> ) ( <listspec> )
  ALTER TABLE ... PARTITION BY NOTHING
  ALTER TABLE ... CONFIGURE ZONE <zoneconfig>

Column qualifiers:
  [CONSTRAINT <constraintname>] {NULL | NOT NULL | UNIQUE | PRIMARY KEY | CHECK (<expr>) | DEFAULT <expr>}
  FAMILY <familyname>, CREATE [IF NOT EXISTS] FAMILY [<familyname>]
  REFERENCES <tablename> [( <colnames...> )]
  COLLATE <collationname>

Zone configurations:
  DISCARD
  USING <var> = <expr> [, ...]
  USING <var> = COPY FROM PARENT [, ...]
  { TO | = } <expr>

`,
		//line sql.y: 1209
		SeeAlso: `WEBDOCS/alter-table.html
`,
	},
	//line sql.y: 1223
	`ALTER PARTITION`: {
		ShortDescription: `apply zone configurations to a partition`,
		//line sql.y: 1224
		Category: hDDL,
		//line sql.y: 1225
		Text: `
ALTER PARTITION <name> <command>

Commands:
  -- Alter a single partition which exists on any of a table's indexes.
  ALTER PARTITION <partition> OF TABLE <tablename> CONFIGURE ZONE <zoneconfig>

  -- Alter a partition of a specific index.
  ALTER PARTITION <partition> OF INDEX <tablename>@<indexname> CONFIGURE ZONE <zoneconfig>

  -- Alter all partitions with the same name across a table's indexes.
  ALTER PARTITION <partition> OF INDEX <tablename>@* CONFIGURE ZONE <zoneconfig>

Zone configurations:
  DISCARD
  USING <var> = <expr> [, ...]
  USING <var> = COPY FROM PARENT [, ...]
  { TO | = } <expr>

`,
		//line sql.y: 1244
		SeeAlso: `WEBDOCS/configure-zone.html
`,
	},
	//line sql.y: 1249
	`ALTER VIEW`: {
		ShortDescription: `change the definition of a view`,
		//line sql.y: 1250
		Category: hDDL,
		//line sql.y: 1251
		Text: `
ALTER VIEW [IF EXISTS] <name> RENAME TO <newname>
`,
		//line sql.y: 1253
		SeeAlso: `WEBDOCS/alter-view.html
`,
	},
	//line sql.y: 1260
	`ALTER SEQUENCE`: {
		ShortDescription: `change the definition of a sequence`,
		//line sql.y: 1261
		Category: hDDL,
		//line sql.y: 1262
		Text: `
ALTER SEQUENCE [IF EXISTS] <name>
  [INCREMENT <increment>]
  [MINVALUE <minvalue> | NO MINVALUE]
  [MAXVALUE <maxvalue> | NO MAXVALUE]
  [START <start>]
  [[NO] CYCLE]
ALTER SEQUENCE [IF EXISTS] <name> RENAME TO <newname>
`,
	},
	//line sql.y: 1285
	`ALTER DATABASE`: {
		ShortDescription: `change the definition of a database`,
		//line sql.y: 1286
		Category: hDDL,
		//line sql.y: 1287
		Text: `
ALTER DATABASE <name> RENAME TO <newname>
`,
		//line sql.y: 1289
		SeeAlso: `WEBDOCS/alter-database.html
`,
	},
	//line sql.y: 1297
	`ALTER RANGE`: {
		ShortDescription: `change the parameters of a range`,
		//line sql.y: 1298
		Category: hDDL,
		//line sql.y: 1299
		Text: `
ALTER RANGE <zonename> <command>

Commands:
  ALTER RANGE ... CONFIGURE ZONE <zoneconfig>

Zone configurations:
  DISCARD
  USING <var> = <expr> [, ...]
  USING <var> = COPY FROM PARENT [, ...]
  { TO | = } <expr>

`,
		//line sql.y: 1311
		SeeAlso: `ALTER TABLE
`,
	},
	//line sql.y: 1316
	`ALTER INDEX`: {
		ShortDescription: `change the definition of an index`,
		//line sql.y: 1317
		Category: hDDL,
		//line sql.y: 1318
		Text: `
ALTER INDEX [IF EXISTS] <idxname> <command>

Commands:
  ALTER INDEX ... RENAME TO <newname>
  ALTER INDEX ... SPLIT AT <selectclause> [WITH EXPIRATION <expr>]
  ALTER INDEX ... UNSPLIT AT <selectclause>
  ALTER INDEX ... UNSPLIT ALL
  ALTER INDEX ... SCATTER [ FROM ( <exprs...> ) TO ( <exprs...> ) ]

Zone configurations:
  DISCARD
  USING <var> = <expr> [, ...]
  USING <var> = COPY FROM PARENT [, ...]
  { TO | = } <expr>

`,
		//line sql.y: 1334
		SeeAlso: `WEBDOCS/alter-index.html
`,
	},
	//line sql.y: 1836
	`BACKUP`: {
		ShortDescription: `back up data to external storage`,
		//line sql.y: 1837
		Category: hCCL,
		//line sql.y: 1838
		Text: `
BACKUP <targets...> TO <location...>
       [ AS OF SYSTEM TIME <expr> ]
       [ INCREMENTAL FROM <location...> ]
       [ WITH <option> [= <value>] [, ...] ]

Targets:
   TABLE <pattern> [, ...]
   DATABASE <databasename> [, ...]

Location:
   "[scheme]://[host]/[path to backup]?[parameters]"

Options:
   INTO_DB
   SKIP_MISSING_FOREIGN_KEYS

`,
		//line sql.y: 1855
		SeeAlso: `RESTORE, WEBDOCS/backup.html
`,
	},
	//line sql.y: 1867
	`RESTORE`: {
		ShortDescription: `restore data from external storage`,
		//line sql.y: 1868
		Category: hCCL,
		//line sql.y: 1869
		Text: `
RESTORE <targets...> FROM <location...>
        [ AS OF SYSTEM TIME <expr> ]
        [ WITH <option> [= <value>] [, ...] ]

Targets:
   TABLE <pattern> [, ...]
   DATABASE <databasename> [, ...]

Locations:
   "[scheme]://[host]/[path to backup]?[parameters]"

Options:
   INTO_DB
   SKIP_MISSING_FOREIGN_KEYS

`,
		//line sql.y: 1885
		SeeAlso: `BACKUP, WEBDOCS/restore.html
`,
	},
	//line sql.y: 1923
	`IMPORT`: {
		ShortDescription: `load data from file in a distributed manner`,
		//line sql.y: 1924
		Category: hCCL,
		//line sql.y: 1925
		Text: `
-- Import both schema and table data:
IMPORT [ TABLE <tablename> FROM ]
       <format> <datafile>
       [ WITH <option> [= <value>] [, ...] ]

-- Import using specific schema, use only table data from external file:
IMPORT TABLE <tablename>
       { ( <elements> ) | CREATE USING <schemafile> }
       <format>
       DATA ( <datafile> [, ...] )
       [ WITH <option> [= <value>] [, ...] ]

Formats:
   CSV
   DELIMITED
   MYSQLDUMP
   PGCOPY
   PGDUMP

Options:
   distributed = '...'
   sstsize = '...'
   temp = '...'
   delimiter = '...'      [CSV, PGCOPY-specific]
   nullif = '...'         [CSV, PGCOPY-specific]
   comment = '...'        [CSV-specific]

`,
		//line sql.y: 1953
		SeeAlso: `CREATE TABLE
`,
	},
	//line sql.y: 1997
	`EXPORT`: {
		ShortDescription: `export data to file in a distributed manner`,
		//line sql.y: 1998
		Category: hCCL,
		//line sql.y: 1999
		Text: `
EXPORT INTO <format> <datafile> [WITH <option> [= value] [,...]] FROM <query>

Formats:
   CSV

Options:
   delimiter = '...'   [CSV-specific]

`,
		//line sql.y: 2008
		SeeAlso: `SELECT
`,
	},
	//line sql.y: 2102
	`CANCEL`: {
		//line sql.y: 2103
		Category: hGroup,
		//line sql.y: 2104
		Text: `CANCEL JOBS, CANCEL QUERIES, CANCEL SESSIONS
`,
	},
	//line sql.y: 2111
	`CANCEL JOBS`: {
		ShortDescription: `cancel background jobs`,
		//line sql.y: 2112
		Category: hMisc,
		//line sql.y: 2113
		Text: `
CANCEL JOBS <selectclause>
CANCEL JOB <jobid>
`,
		//line sql.y: 2116
		SeeAlso: `SHOW JOBS, PAUSE JOBS, RESUME JOBS
`,
	},
	//line sql.y: 2134
	`CANCEL QUERIES`: {
		ShortDescription: `cancel running queries`,
		//line sql.y: 2135
		Category: hMisc,
		//line sql.y: 2136
		Text: `
CANCEL QUERIES [IF EXISTS] <selectclause>
CANCEL QUERY [IF EXISTS] <expr>
`,
		//line sql.y: 2139
		SeeAlso: `SHOW QUERIES
`,
	},
	//line sql.y: 2170
	`CANCEL SESSIONS`: {
		ShortDescription: `cancel open sessions`,
		//line sql.y: 2171
		Category: hMisc,
		//line sql.y: 2172
		Text: `
CANCEL SESSIONS [IF EXISTS] <selectclause>
CANCEL SESSION [IF EXISTS] <sessionid>
`,
		//line sql.y: 2175
		SeeAlso: `SHOW SESSIONS
`,
	},
	//line sql.y: 2245
	`CREATE`: {
		//line sql.y: 2246
		Category: hGroup,
		//line sql.y: 2247
		Text: `
CREATE DATABASE, CREATE TABLE, CREATE INDEX, CREATE TABLE AS,
CREATE USER, CREATE VIEW, CREATE SEQUENCE, CREATE STATISTICS,
CREATE ROLE
`,
	},
	//line sql.y: 2327
	`CREATE STATISTICS`: {
		ShortDescription: `create a new table statistic`,
		//line sql.y: 2328
		Category: hMisc,
		//line sql.y: 2329
		Text: `
CREATE STATISTICS <statisticname>
  [ON <colname> [, ...]]
  FROM <tablename> [AS OF SYSTEM TIME <expr>]
`,
	},
	//line sql.y: 2472
	`DELETE`: {
		ShortDescription: `delete rows from a table`,
		//line sql.y: 2473
		Category: hDML,
		//line sql.y: 2474
		Text: `DELETE FROM <tablename> [WHERE <expr>]
              [ORDER BY <exprs...>]
              [LIMIT <expr>]
              [RETURNING <exprs...>]
`,
		//line sql.y: 2478
		SeeAlso: `WEBDOCS/delete.html
`,
	},
	//line sql.y: 2498
	`DISCARD`: {
		ShortDescription: `reset the session to its initial state`,
		//line sql.y: 2499
		Category: hCfg,
		//line sql.y: 2500
		Text: `DISCARD ALL
`,
	},
	//line sql.y: 2512
	`DROP`: {
		//line sql.y: 2513
		Category: hGroup,
		//line sql.y: 2514
		Text: `
DROP DATABASE, DROP INDEX, DROP TABLE, DROP VIEW, DROP SEQUENCE,
DROP USER, DROP ROLE
`,
	},
	//line sql.y: 2530
	`DROP VIEW`: {
		ShortDescription: `remove a view`,
		//line sql.y: 2531
		Category: hDDL,
		//line sql.y: 2532
		Text: `DROP VIEW [IF EXISTS] <tablename> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 2533
		SeeAlso: `WEBDOCS/drop-index.html
`,
	},
	//line sql.y: 2545
	`DROP SEQUENCE`: {
		ShortDescription: `remove a sequence`,
		//line sql.y: 2546
		Category: hDDL,
		//line sql.y: 2547
		Text: `DROP SEQUENCE [IF EXISTS] <sequenceName> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 2548
		SeeAlso: `DROP
`,
	},
	//line sql.y: 2560
	`DROP TABLE`: {
		ShortDescription: `remove a table`,
		//line sql.y: 2561
		Category: hDDL,
		//line sql.y: 2562
		Text: `DROP TABLE [IF EXISTS] <tablename> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 2563
		SeeAlso: `WEBDOCS/drop-table.html
`,
	},
	//line sql.y: 2575
	`DROP INDEX`: {
		ShortDescription: `remove an index`,
		//line sql.y: 2576
		Category: hDDL,
		//line sql.y: 2577
		Text: `DROP INDEX [CONCURRENTLY] [IF EXISTS] <idxname> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 2578
		SeeAlso: `WEBDOCS/drop-index.html
`,
	},
	//line sql.y: 2600
	`DROP DATABASE`: {
		ShortDescription: `remove a database`,
		//line sql.y: 2601
		Category: hDDL,
		//line sql.y: 2602
		Text: `DROP DATABASE [IF EXISTS] <databasename> [CASCADE | RESTRICT]
`,
		//line sql.y: 2603
		SeeAlso: `WEBDOCS/drop-database.html
`,
	},
	//line sql.y: 2623
	`DROP ROLE`: {
		ShortDescription: `remove a user`,
		//line sql.y: 2624
		Category: hPriv,
		//line sql.y: 2625
		Text: `DROP ROLE [IF EXISTS] <user> [, ...]
`,
		//line sql.y: 2626
		SeeAlso: `CREATE ROLE, SHOW ROLE
`,
	},
	//line sql.y: 2650
	`EXPLAIN`: {
		ShortDescription: `show the logical plan of a query`,
		//line sql.y: 2651
		Category: hMisc,
		//line sql.y: 2652
		Text: `
EXPLAIN <statement>
EXPLAIN ([PLAN ,] <planoptions...> ) <statement>
EXPLAIN [ANALYZE] (DISTSQL) <statement>
EXPLAIN ANALYZE [(DISTSQL)] <statement>

Explainable statements:
    SELECT, CREATE, DROP, ALTER, INSERT, UPSERT, UPDATE, DELETE,
    SHOW, EXPLAIN

Plan options:
    TYPES, VERBOSE, OPT

`,
		//line sql.y: 2665
		SeeAlso: `WEBDOCS/explain.html
`,
	},
	//line sql.y: 2772
	`PREPARE`: {
		ShortDescription: `prepare a statement for later execution`,
		//line sql.y: 2773
		Category: hMisc,
		//line sql.y: 2774
		Text: `PREPARE <name> [ ( <types...> ) ] AS <query>
`,
		//line sql.y: 2775
		SeeAlso: `EXECUTE, DEALLOCATE, DISCARD
`,
	},
	//line sql.y: 2806
	`EXECUTE`: {
		ShortDescription: `execute a statement prepared previously`,
		//line sql.y: 2807
		Category: hMisc,
		//line sql.y: 2808
		Text: `EXECUTE <name> [ ( <exprs...> ) ]
`,
		//line sql.y: 2809
		SeeAlso: `PREPARE, DEALLOCATE, DISCARD
`,
	},
	//line sql.y: 2839
	`DEALLOCATE`: {
		ShortDescription: `remove a prepared statement`,
		//line sql.y: 2840
		Category: hMisc,
		//line sql.y: 2841
		Text: `DEALLOCATE [PREPARE] { <name> | ALL }
`,
		//line sql.y: 2842
		SeeAlso: `PREPARE, EXECUTE, DISCARD
`,
	},
	//line sql.y: 2862
	`GRANT`: {
		ShortDescription: `define access privileges and role memberships`,
		//line sql.y: 2863
		Category: hPriv,
		//line sql.y: 2864
		Text: `
Grant privileges:
  GRANT {ALL | <privileges...> } ON <targets...> TO <grantees...>
Grant role membership (CCL only):
  GRANT <roles...> TO <grantees...> [WITH ADMIN OPTION]

Privileges:
  CREATE, DROP, GRANT, SELECT, INSERT, DELETE, UPDATE

Targets:
  DATABASE <databasename> [, ...]
  [TABLE] [<databasename> .] { <tablename> | * } [, ...]

`,
		//line sql.y: 2877
		SeeAlso: `REVOKE, WEBDOCS/grant.html
`,
	},
	//line sql.y: 2893
	`REVOKE`: {
		ShortDescription: `remove access privileges and role memberships`,
		//line sql.y: 2894
		Category: hPriv,
		//line sql.y: 2895
		Text: `
Revoke privileges:
  REVOKE {ALL | <privileges...> } ON <targets...> FROM <grantees...>
Revoke role membership (CCL only):
  REVOKE [ADMIN OPTION FOR] <roles...> FROM <grantees...>

Privileges:
  CREATE, DROP, GRANT, SELECT, INSERT, DELETE, UPDATE

Targets:
  DATABASE <databasename> [, <databasename>]...
  [TABLE] [<databasename> .] { <tablename> | * } [, ...]

`,
		//line sql.y: 2908
		SeeAlso: `GRANT, WEBDOCS/revoke.html
`,
	},
	//line sql.y: 2962
	`RESET`: {
		ShortDescription: `reset a session variable to its default value`,
		//line sql.y: 2963
		Category: hCfg,
		//line sql.y: 2964
		Text: `RESET [SESSION] <var>
`,
		//line sql.y: 2965
		SeeAlso: `RESET CLUSTER SETTING, WEBDOCS/set-vars.html
`,
	},
	//line sql.y: 2977
	`RESET CLUSTER SETTING`: {
		ShortDescription: `reset a cluster setting to its default value`,
		//line sql.y: 2978
		Category: hCfg,
		//line sql.y: 2979
		Text: `RESET CLUSTER SETTING <var>
`,
		//line sql.y: 2980
		SeeAlso: `SET CLUSTER SETTING, RESET
`,
	},
	//line sql.y: 2989
	`USE`: {
		ShortDescription: `set the current database`,
		//line sql.y: 2990
		Category: hCfg,
		//line sql.y: 2991
		Text: `USE <dbname>

"USE <dbname>" is an alias for "SET [SESSION] database = <dbname>".
`,
		//line sql.y: 2994
		SeeAlso: `SET SESSION, WEBDOCS/set-vars.html
`,
	},
	//line sql.y: 3015
	`SCRUB`: {
		ShortDescription: `run checks against databases or tables`,
		//line sql.y: 3016
		Category: hExperimental,
		//line sql.y: 3017
		Text: `
EXPERIMENTAL SCRUB TABLE <table> ...
EXPERIMENTAL SCRUB DATABASE <database>

The various checks that ca be run with SCRUB includes:
  - Physical table data (encoding)
  - Secondary index integrity
  - Constraint integrity (NOT NULL, CHECK, FOREIGN KEY, UNIQUE)
`,
		//line sql.y: 3025
		SeeAlso: `SCRUB TABLE, SCRUB DATABASE
`,
	},
	//line sql.y: 3031
	`SCRUB DATABASE`: {
		ShortDescription: `run scrub checks on a database`,
		//line sql.y: 3032
		Category: hExperimental,
		//line sql.y: 3033
		Text: `
EXPERIMENTAL SCRUB DATABASE <database>
                            [AS OF SYSTEM TIME <expr>]

All scrub checks will be run on the database. This includes:
  - Physical table data (encoding)
  - Secondary index integrity
  - Constraint integrity (NOT NULL, CHECK, FOREIGN KEY, UNIQUE)
`,
		//line sql.y: 3041
		SeeAlso: `SCRUB TABLE, SCRUB
`,
	},
	//line sql.y: 3049
	`SCRUB TABLE`: {
		ShortDescription: `run scrub checks on a table`,
		//line sql.y: 3050
		Category: hExperimental,
		//line sql.y: 3051
		Text: `
SCRUB TABLE <tablename>
            [AS OF SYSTEM TIME <expr>]
            [WITH OPTIONS <option> [, ...]]

Options:
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS INDEX ALL
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS INDEX (<index>...)
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS CONSTRAINT ALL
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS CONSTRAINT (<constraint>...)
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS PHYSICAL
`,
		//line sql.y: 3062
		SeeAlso: `SCRUB DATABASE, SRUB
`,
	},
	//line sql.y: 3117
	`SET CLUSTER SETTING`: {
		ShortDescription: `change a cluster setting`,
		//line sql.y: 3118
		Category: hCfg,
		//line sql.y: 3119
		Text: `SET CLUSTER SETTING <var> { TO | = } <value>
`,
		//line sql.y: 3120
		SeeAlso: `SHOW CLUSTER SETTING, RESET CLUSTER SETTING, SET SESSION,
WEBDOCS/cluster-settings.html
`,
	},
	//line sql.y: 3141
	`SET SESSION`: {
		ShortDescription: `change a session variable`,
		//line sql.y: 3142
		Category: hCfg,
		//line sql.y: 3143
		Text: `
SET [SESSION] <var> { TO | = } <values...>
SET [SESSION] TIME ZONE <tz>
SET [SESSION] CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL { SNAPSHOT | SERIALIZABLE }
SET [SESSION] TRACING { TO | = } { on | off | cluster | local | kv | results } [,...]

`,
		//line sql.y: 3149
		SeeAlso: `SHOW SESSION, RESET, DISCARD, SHOW, SET CLUSTER SETTING, SET TRANSACTION,
WEBDOCS/set-vars.html
`,
	},
	//line sql.y: 3166
	`SET TRANSACTION`: {
		ShortDescription: `configure the transaction settings`,
		//line sql.y: 3167
		Category: hTxn,
		//line sql.y: 3168
		Text: `
SET [SESSION] TRANSACTION <txnparameters...>

Transaction parameters:
   ISOLATION LEVEL { SNAPSHOT | SERIALIZABLE }
   PRIORITY { LOW | NORMAL | HIGH }

`,
		//line sql.y: 3175
		SeeAlso: `SHOW TRANSACTION, SET SESSION,
WEBDOCS/set-transaction.html
`,
	},
	//line sql.y: 3367
	`SHOW`: {
		//line sql.y: 3368
		Category: hGroup,
		//line sql.y: 3369
		Text: `
SHOW BACKUP, SHOW CLUSTER SETTING, SHOW COLUMNS, SHOW CONSTRAINTS,
SHOW CREATE, SHOW DATABASES, SHOW HISTOGRAM, SHOW INDEXES, SHOW
PARTITIONS, SHOW JOBS, SHOW QUERIES, SHOW RANGE, SHOW RANGES,
SHOW ROLES, SHOW SCHEMAS, SHOW SEQUENCES, SHOW SESSION, SHOW SESSIONS,
SHOW STATISTICS, SHOW SYNTAX, SHOW TABLES, SHOW TRACE SHOW TRANSACTION, SHOW USERS
`,
	},
	//line sql.y: 3428
	`SHOW SESSION`: {
		ShortDescription: `display session variables`,
		//line sql.y: 3429
		Category: hCfg,
		//line sql.y: 3430
		Text: `SHOW [SESSION] { <var> | ALL }
`,
		//line sql.y: 3431
		SeeAlso: `WEBDOCS/show-vars.html
`,
	},
	//line sql.y: 3452
	`SHOW STATISTICS`: {
		ShortDescription: `display table statistics (experimental)`,
		//line sql.y: 3453
		Category: hExperimental,
		//line sql.y: 3454
		Text: `SHOW STATISTICS [USING JSON] FOR TABLE <table_name>

Returns the available statistics for a table.
The statistics can include a histogram ID, which can
be used with SHOW HISTOGRAM.
If USING JSON is specified, the statistics and histograms
are encoded in JSON format.
`,
		//line sql.y: 3461
		SeeAlso: `SHOW HISTOGRAM
`,
	},
	//line sql.y: 3474
	`SHOW HISTOGRAM`: {
		ShortDescription: `display histogram (experimental)`,
		//line sql.y: 3475
		Category: hExperimental,
		//line sql.y: 3476
		Text: `SHOW HISTOGRAM <histogram_id>

Returns the data in the histogram with the
given ID (as returned by SHOW STATISTICS).
`,
		//line sql.y: 3480
		SeeAlso: `SHOW STATISTICS
`,
	},
	//line sql.y: 3493
	`SHOW BACKUP`: {
		ShortDescription: `list backup contents`,
		//line sql.y: 3494
		Category: hCCL,
		//line sql.y: 3495
		Text: `SHOW BACKUP [SCHEMAS|FILES|RANGES] <location>
`,
		//line sql.y: 3496
		SeeAlso: `WEBDOCS/show-backup.html
`,
	},
	//line sql.y: 3535
	`SHOW CLUSTER SETTING`: {
		ShortDescription: `display cluster settings`,
		//line sql.y: 3536
		Category: hCfg,
		//line sql.y: 3537
		Text: `
SHOW CLUSTER SETTING <var>
SHOW [ PUBLIC | ALL ] CLUSTER SETTINGS
`,
		//line sql.y: 3540
		SeeAlso: `WEBDOCS/cluster-settings.html
`,
	},
	//line sql.y: 3566
	`SHOW COLUMNS`: {
		ShortDescription: `list columns in relation`,
		//line sql.y: 3567
		Category: hDDL,
		//line sql.y: 3568
		Text: `SHOW COLUMNS FROM <tablename>
`,
		//line sql.y: 3569
		SeeAlso: `WEBDOCS/show-columns.html
`,
	},
	//line sql.y: 3577
	`SHOW PARTITIONS`: {
		ShortDescription: `list partition information`,
		//line sql.y: 3578
		Category: hDDL,
		//line sql.y: 3579
		Text: `SHOW PARTITIONS FROM { TABLE <table> | INDEX <index> | DATABASE <database> }
`,
		//line sql.y: 3580
		SeeAlso: `WEBDOCS/show-partitions.html
`,
	},
	//line sql.y: 3600
	`SHOW DATABASES`: {
		ShortDescription: `list databases`,
		//line sql.y: 3601
		Category: hDDL,
		//line sql.y: 3602
		Text: `SHOW DATABASES
`,
		//line sql.y: 3603
		SeeAlso: `WEBDOCS/show-databases.html
`,
	},
	//line sql.y: 3611
	`SHOW GRANTS`: {
		ShortDescription: `list grants`,
		//line sql.y: 3612
		Category: hPriv,
		//line sql.y: 3613
		Text: `
Show privilege grants:
  SHOW GRANTS [ON <targets...>] [FOR <users...>]
Show role grants:
  SHOW GRANTS ON ROLE [<roles...>] [FOR <grantees...>]

`,
		//line sql.y: 3619
		SeeAlso: `WEBDOCS/show-grants.html
`,
	},
	//line sql.y: 3632
	`SHOW INDEXES`: {
		ShortDescription: `list indexes`,
		//line sql.y: 3633
		Category: hDDL,
		//line sql.y: 3634
		Text: `SHOW INDEXES FROM { <tablename> | DATABASE <database_name> } [WITH COMMENT]
`,
		//line sql.y: 3635
		SeeAlso: `WEBDOCS/show-index.html
`,
	},
	//line sql.y: 3665
	`SHOW CONSTRAINTS`: {
		ShortDescription: `list constraints`,
		//line sql.y: 3666
		Category: hDDL,
		//line sql.y: 3667
		Text: `SHOW CONSTRAINTS FROM <tablename>
`,
		//line sql.y: 3668
		SeeAlso: `WEBDOCS/show-constraints.html
`,
	},
	//line sql.y: 3681
	`SHOW QUERIES`: {
		ShortDescription: `list running queries`,
		//line sql.y: 3682
		Category: hMisc,
		//line sql.y: 3683
		Text: `SHOW [ALL] [CLUSTER | LOCAL] QUERIES
`,
		//line sql.y: 3684
		SeeAlso: `CANCEL QUERIES
`,
	},
	//line sql.y: 3705
	`SHOW JOBS`: {
		ShortDescription: `list background jobs`,
		//line sql.y: 3706
		Category: hMisc,
		//line sql.y: 3707
		Text: `
SHOW [AUTOMATIC] JOBS
SHOW JOB <jobid>
`,
		//line sql.y: 3710
		SeeAlso: `CANCEL JOBS, PAUSE JOBS, RESUME JOBS
`,
	},
	//line sql.y: 3750
	`SHOW TRACE`: {
		ShortDescription: `display an execution trace`,
		//line sql.y: 3751
		Category: hMisc,
		//line sql.y: 3752
		Text: `
SHOW [COMPACT] [KV] TRACE FOR SESSION
`,
		//line sql.y: 3754
		SeeAlso: `EXPLAIN
`,
	},
	//line sql.y: 3777
	`SHOW SESSIONS`: {
		ShortDescription: `list open client sessions`,
		//line sql.y: 3778
		Category: hMisc,
		//line sql.y: 3779
		Text: `SHOW [ALL] [CLUSTER | LOCAL] SESSIONS
`,
		//line sql.y: 3780
		SeeAlso: `CANCEL SESSIONS
`,
	},
	//line sql.y: 3793
	`SHOW TABLES`: {
		ShortDescription: `list tables`,
		//line sql.y: 3794
		Category: hDDL,
		//line sql.y: 3795
		Text: `SHOW TABLES [FROM <databasename> [ . <schemaname> ] ] [WITH COMMENT]
`,
		//line sql.y: 3796
		SeeAlso: `WEBDOCS/show-tables.html
`,
	},
	//line sql.y: 3828
	`SHOW SCHEMAS`: {
		ShortDescription: `list schemas`,
		//line sql.y: 3829
		Category: hDDL,
		//line sql.y: 3830
		Text: `SHOW SCHEMAS [FROM <databasename> ]
`,
	},
	//line sql.y: 3842
	`SHOW SEQUENCES`: {
		ShortDescription: `list sequences`,
		//line sql.y: 3843
		Category: hDDL,
		//line sql.y: 3844
		Text: `SHOW SEQUENCES [FROM <databasename> ]
`,
	},
	//line sql.y: 3856
	`SHOW SYNTAX`: {
		ShortDescription: `analyze SQL syntax`,
		//line sql.y: 3857
		Category: hMisc,
		//line sql.y: 3858
		Text: `SHOW SYNTAX <string>
`,
	},
	//line sql.y: 3867
	`SHOW SAVEPOINT`: {
		ShortDescription: `display current savepoint properties`,
		//line sql.y: 3868
		Category: hCfg,
		//line sql.y: 3869
		Text: `SHOW SAVEPOINT STATUS
`,
	},
	//line sql.y: 3877
	`SHOW TRANSACTION`: {
		ShortDescription: `display current transaction properties`,
		//line sql.y: 3878
		Category: hCfg,
		//line sql.y: 3879
		Text: `SHOW TRANSACTION {ISOLATION LEVEL | PRIORITY | STATUS}
`,
		//line sql.y: 3880
		SeeAlso: `WEBDOCS/show-transaction.html
`,
	},
	//line sql.y: 3899
	`SHOW CREATE`: {
		ShortDescription: `display the CREATE statement for a table, sequence or view`,
		//line sql.y: 3900
		Category: hDDL,
		//line sql.y: 3901
		Text: `SHOW CREATE [ TABLE | SEQUENCE | VIEW ] <tablename>
`,
		//line sql.y: 3902
		SeeAlso: `WEBDOCS/show-create-table.html
`,
	},
	//line sql.y: 3920
	`SHOW USERS`: {
		ShortDescription: `list defined users`,
		//line sql.y: 3921
		Category: hPriv,
		//line sql.y: 3922
		Text: `SHOW USERS
`,
		//line sql.y: 3923
		SeeAlso: `CREATE USER, DROP USER, WEBDOCS/show-users.html
`,
	},
	//line sql.y: 3931
	`SHOW ROLES`: {
		ShortDescription: `list defined roles`,
		//line sql.y: 3932
		Category: hPriv,
		//line sql.y: 3933
		Text: `SHOW ROLES
`,
		//line sql.y: 3934
		SeeAlso: `CREATE ROLE, ALTER ROLE, DROP ROLE
`,
	},
	//line sql.y: 3990
	`SHOW RANGE`: {
		ShortDescription: `show range information for a row`,
		//line sql.y: 3991
		Category: hMisc,
		//line sql.y: 3992
		Text: `
SHOW RANGE FROM TABLE <tablename> FOR ROW (row, value, ...)
SHOW RANGE FROM INDEX [ <tablename> @ ] <indexname> FOR ROW (row, value, ...)
`,
	},
	//line sql.y: 4013
	`SHOW RANGES`: {
		ShortDescription: `list ranges`,
		//line sql.y: 4014
		Category: hMisc,
		//line sql.y: 4015
		Text: `
SHOW RANGES FROM TABLE <tablename>
SHOW RANGES FROM INDEX [ <tablename> @ ] <indexname>
`,
	},
	//line sql.y: 4252
	`PAUSE JOBS`: {
		ShortDescription: `pause background jobs`,
		//line sql.y: 4253
		Category: hMisc,
		//line sql.y: 4254
		Text: `
PAUSE JOBS <selectclause>
PAUSE JOB <jobid>
`,
		//line sql.y: 4257
		SeeAlso: `SHOW JOBS, CANCEL JOBS, RESUME JOBS
`,
	},
	//line sql.y: 4274
	`CREATE SCHEMA`: {
		ShortDescription: `create a new schema (not yet supported)`,
		//line sql.y: 4275
		Category: hDDL,
		//line sql.y: 4276
		Text: `
CREATE SCHEMA [IF NOT EXISTS] <schemaname>
`,
	},
	//line sql.y: 4294
	`CREATE TABLE`: {
		ShortDescription: `create a new table`,
		//line sql.y: 4295
		Category: hDDL,
		//line sql.y: 4296
		Text: `
CREATE [[GLOBAL | LOCAL] {TEMPORARY | TEMP}] TABLE [IF NOT EXISTS] <tablename> ( <elements...> ) [<interleave>] [<on_commit>]
CREATE [[GLOBAL | LOCAL] {TEMPORARY | TEMP}] TABLE [IF NOT EXISTS] <tablename> [( <colnames...> )] AS <source> [<interleave>] [<on commit>]

Table elements:
   <name> <type> [<qualifiers...>]
   [UNIQUE | INVERTED] INDEX [<name>] ( <colname> [ASC | DESC] [, ...] )
                           [USING HASH WITH BUCKET_COUNT = <shard_buckets>] [{STORING | INCLUDE | COVERING} ( <colnames...> )] [<interleave>]
   FAMILY [<name>] ( <colnames...> )
   [CONSTRAINT <name>] <constraint>

Table constraints:
   PRIMARY KEY ( <colnames...> ) [USING HASH WITH BUCKET_COUNT = <shard_buckets>]
   FOREIGN KEY ( <colnames...> ) REFERENCES <tablename> [( <colnames...> )] [ON DELETE {NO ACTION | RESTRICT}] [ON UPDATE {NO ACTION | RESTRICT}]
   UNIQUE ( <colnames... ) [{STORING | INCLUDE | COVERING} ( <colnames...> )] [<interleave>]
   CHECK ( <expr> )

Column qualifiers:
  [CONSTRAINT <constraintname>] {NULL | NOT NULL | UNIQUE | PRIMARY KEY | CHECK (<expr>) | DEFAULT <expr>}
  FAMILY <familyname>, CREATE [IF NOT EXISTS] FAMILY [<familyname>]
  REFERENCES <tablename> [( <colnames...> )] [ON DELETE {NO ACTION | RESTRICT}] [ON UPDATE {NO ACTION | RESTRICT}]
  COLLATE <collationname>
  AS ( <expr> ) STORED

Interleave clause:
   INTERLEAVE IN PARENT <tablename> ( <colnames...> ) [CASCADE | RESTRICT]

On commit clause:
   ON COMMIT {PRESERVE ROWS | DROP | DELETE ROWS}

`,
		//line sql.y: 4326
		SeeAlso: `SHOW TABLES, CREATE VIEW, SHOW CREATE,
WEBDOCS/create-table.html
WEBDOCS/create-table-as.html
`,
	},
	//line sql.y: 5103
	`CREATE SEQUENCE`: {
		ShortDescription: `create a new sequence`,
		//line sql.y: 5104
		Category: hDDL,
		//line sql.y: 5105
		Text: `
CREATE [TEMPORARY | TEMP] SEQUENCE <seqname>
  [INCREMENT <increment>]
  [MINVALUE <minvalue> | NO MINVALUE]
  [MAXVALUE <maxvalue> | NO MAXVALUE]
  [START [WITH] <start>]
  [CACHE <cache>]
  [NO CYCLE]
  [VIRTUAL]

`,
		//line sql.y: 5115
		SeeAlso: `CREATE TABLE
`,
	},
	//line sql.y: 5180
	`TRUNCATE`: {
		ShortDescription: `empty one or more tables`,
		//line sql.y: 5181
		Category: hDML,
		//line sql.y: 5182
		Text: `TRUNCATE [TABLE] <tablename> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 5183
		SeeAlso: `WEBDOCS/truncate.html
`,
	},
	//line sql.y: 5201
	`CREATE ROLE`: {
		ShortDescription: `define a new role`,
		//line sql.y: 5202
		Category: hPriv,
		//line sql.y: 5203
		Text: `CREATE ROLE [IF NOT EXISTS] <name> [ [WITH] <OPTIONS...> ]
`,
		//line sql.y: 5204
		SeeAlso: `ALTER ROLE, DROP ROLE, SHOW ROLES
`,
	},
	//line sql.y: 5216
	`ALTER ROLE`: {
		ShortDescription: `alter a role`,
		//line sql.y: 5217
		Category: hPriv,
		//line sql.y: 5218
		Text: `ALTER ROLE <name> [WITH] <options...>
`,
		//line sql.y: 5219
		SeeAlso: `CREATE ROLE, DROP ROLE, SHOW ROLES
`,
	},
	//line sql.y: 5248
	`CREATE VIEW`: {
		ShortDescription: `create a new view`,
		//line sql.y: 5249
		Category: hDDL,
		//line sql.y: 5250
		Text: `CREATE [TEMPORARY | TEMP] VIEW <viewname> [( <colnames...> )] AS <source>
`,
		//line sql.y: 5251
		SeeAlso: `CREATE TABLE, SHOW CREATE, WEBDOCS/create-view.html
`,
	},
	//line sql.y: 5348
	`CREATE INDEX`: {
		ShortDescription: `create a new index`,
		//line sql.y: 5349
		Category: hDDL,
		//line sql.y: 5350
		Text: `
CREATE [UNIQUE | INVERTED] INDEX [CONCURRENTLY] [IF NOT EXISTS] [<idxname>]
       ON <tablename> ( <colname> [ASC | DESC] [, ...] )
       [USING HASH WITH BUCKET_COUNT = <shard_buckets>] [STORING ( <colnames...> )] [<interleave>]

Interleave clause:
   INTERLEAVE IN PARENT <tablename> ( <colnames...> ) [CASCADE | RESTRICT]

`,
		//line sql.y: 5358
		SeeAlso: `CREATE TABLE, SHOW INDEXES, SHOW CREATE,
WEBDOCS/create-index.html
`,
	},
	//line sql.y: 5592
	`RELEASE`: {
		ShortDescription: `complete a sub-transaction`,
		//line sql.y: 5593
		Category: hTxn,
		//line sql.y: 5594
		Text: `RELEASE [SAVEPOINT] <savepoint name>
`,
		//line sql.y: 5595
		SeeAlso: `SAVEPOINT, WEBDOCS/savepoint.html
`,
	},
	//line sql.y: 5603
	`RESUME JOBS`: {
		ShortDescription: `resume background jobs`,
		//line sql.y: 5604
		Category: hMisc,
		//line sql.y: 5605
		Text: `
RESUME JOBS <selectclause>
RESUME JOB <jobid>
`,
		//line sql.y: 5608
		SeeAlso: `SHOW JOBS, CANCEL JOBS, PAUSE JOBS
`,
	},
	//line sql.y: 5625
	`SAVEPOINT`: {
		ShortDescription: `start a sub-transaction`,
		//line sql.y: 5626
		Category: hTxn,
		//line sql.y: 5627
		Text: `SAVEPOINT <savepoint name>
`,
		//line sql.y: 5628
		SeeAlso: `RELEASE, WEBDOCS/savepoint.html
`,
	},
	//line sql.y: 5643
	`BEGIN`: {
		ShortDescription: `start a transaction`,
		//line sql.y: 5644
		Category: hTxn,
		//line sql.y: 5645
		Text: `
BEGIN [TRANSACTION] [ <txnparameter> [[,] ...] ]
START TRANSACTION [ <txnparameter> [[,] ...] ]

Transaction parameters:
   ISOLATION LEVEL { SNAPSHOT | SERIALIZABLE }
   PRIORITY { LOW | NORMAL | HIGH }

`,
		//line sql.y: 5653
		SeeAlso: `COMMIT, ROLLBACK, WEBDOCS/begin-transaction.html
`,
	},
	//line sql.y: 5666
	`COMMIT`: {
		ShortDescription: `commit the current transaction`,
		//line sql.y: 5667
		Category: hTxn,
		//line sql.y: 5668
		Text: `
COMMIT [TRANSACTION]
END [TRANSACTION]
`,
		//line sql.y: 5671
		SeeAlso: `BEGIN, ROLLBACK, WEBDOCS/commit-transaction.html
`,
	},
	//line sql.y: 5695
	`ROLLBACK`: {
		ShortDescription: `abort the current (sub-)transaction`,
		//line sql.y: 5696
		Category: hTxn,
		//line sql.y: 5697
		Text: `
ROLLBACK [TRANSACTION]
ROLLBACK [TRANSACTION] TO [SAVEPOINT] <savepoint name>
`,
		//line sql.y: 5700
		SeeAlso: `BEGIN, COMMIT, SAVEPOINT, WEBDOCS/rollback-transaction.html
`,
	},
	//line sql.y: 5800
	`CREATE DATABASE`: {
		ShortDescription: `create a new database`,
		//line sql.y: 5801
		Category: hDDL,
		//line sql.y: 5802
		Text: `CREATE DATABASE [IF NOT EXISTS] <name>
`,
		//line sql.y: 5803
		SeeAlso: `WEBDOCS/create-database.html
`,
	},
	//line sql.y: 5872
	`INSERT`: {
		ShortDescription: `create new rows in a table`,
		//line sql.y: 5873
		Category: hDML,
		//line sql.y: 5874
		Text: `
INSERT INTO <tablename> [[AS] <name>] [( <colnames...> )]
       <selectclause>
       [ON CONFLICT [( <colnames...> )] {DO UPDATE SET ... [WHERE <expr>] | DO NOTHING}]
       [RETURNING <exprs...>]
`,
		//line sql.y: 5879
		SeeAlso: `UPSERT, UPDATE, DELETE, WEBDOCS/insert.html
`,
	},
	//line sql.y: 5898
	`UPSERT`: {
		ShortDescription: `create or replace rows in a table`,
		//line sql.y: 5899
		Category: hDML,
		//line sql.y: 5900
		Text: `
UPSERT INTO <tablename> [AS <name>] [( <colnames...> )]
       <selectclause>
       [RETURNING <exprs...>]
`,
		//line sql.y: 5904
		SeeAlso: `INSERT, UPDATE, DELETE, WEBDOCS/upsert.html
`,
	},
	//line sql.y: 6015
	`UPDATE`: {
		ShortDescription: `update rows of a table`,
		//line sql.y: 6016
		Category: hDML,
		//line sql.y: 6017
		Text: `
UPDATE <tablename> [[AS] <name>]
       SET ...
       [WHERE <expr>]
       [ORDER BY <exprs...>]
       [LIMIT <expr>]
       [RETURNING <exprs...>]
`,
		//line sql.y: 6024
		SeeAlso: `INSERT, UPSERT, DELETE, WEBDOCS/update.html
`,
	},
	//line sql.y: 6249
	`<SELECTCLAUSE>`: {
		ShortDescription: `access tabular data`,
		//line sql.y: 6250
		Category: hDML,
		//line sql.y: 6251
		Text: `
Select clause:
  TABLE <tablename>
  VALUES ( <exprs...> ) [ , ... ]
  SELECT ... [ { INTERSECT | UNION | EXCEPT } [ ALL | DISTINCT ] <selectclause> ]
`,
	},
	//line sql.y: 6262
	`SELECT`: {
		ShortDescription: `retrieve rows from a data source and compute a result`,
		//line sql.y: 6263
		Category: hDML,
		//line sql.y: 6264
		Text: `
SELECT [DISTINCT [ ON ( <expr> [ , ... ] ) ] ]
       { <expr> [[AS] <name>] | [ [<dbname>.] <tablename>. ] * } [, ...]
       [ FROM <source> ]
       [ WHERE <expr> ]
       [ GROUP BY <expr> [ , ... ] ]
       [ HAVING <expr> ]
       [ WINDOW <name> AS ( <definition> ) ]
       [ { UNION | INTERSECT | EXCEPT } [ ALL | DISTINCT ] <selectclause> ]
       [ ORDER BY <expr> [ ASC | DESC ] [, ...] ]
       [ LIMIT { <expr> | ALL } ]
       [ OFFSET <expr> [ ROW | ROWS ] ]
`,
		//line sql.y: 6276
		SeeAlso: `WEBDOCS/select-clause.html
`,
	},
	//line sql.y: 6351
	`TABLE`: {
		ShortDescription: `select an entire table`,
		//line sql.y: 6352
		Category: hDML,
		//line sql.y: 6353
		Text: `TABLE <tablename>
`,
		//line sql.y: 6354
		SeeAlso: `SELECT, VALUES, WEBDOCS/table-expressions.html
`,
	},
	//line sql.y: 6676
	`VALUES`: {
		ShortDescription: `select a given set of values`,
		//line sql.y: 6677
		Category: hDML,
		//line sql.y: 6678
		Text: `VALUES ( <exprs...> ) [, ...]
`,
		//line sql.y: 6679
		SeeAlso: `SELECT, TABLE, WEBDOCS/table-expressions.html
`,
	},
	//line sql.y: 6788
	`<SOURCE>`: {
		ShortDescription: `define a data source for SELECT`,
		//line sql.y: 6789
		Category: hDML,
		//line sql.y: 6790
		Text: `
Data sources:
  <tablename> [ @ { <idxname> | <indexflags> } ]
  <tablefunc> ( <exprs...> )
  ( { <selectclause> | <source> } )
  <source> [AS] <alias> [( <colnames...> )]
  <source> [ <jointype> ] JOIN <source> ON <expr>
  <source> [ <jointype> ] JOIN <source> USING ( <colnames...> )
  <source> NATURAL [ <jointype> ] JOIN <source>
  <source> CROSS JOIN <source>
  <source> WITH ORDINALITY
  '[' EXPLAIN ... ']'
  '[' SHOW ... ']'

Index flags:
  '{' FORCE_INDEX = <idxname> [, ...] '}'
  '{' NO_INDEX_JOIN [, ...] '}'
  '{' IGNORE_FOREIGN_KEYS [, ...] '}'

Join types:
  { INNER | { LEFT | RIGHT | FULL } [OUTER] } [ { HASH | MERGE | LOOKUP } ]

`,
		//line sql.y: 6812
		SeeAlso: `WEBDOCS/table-expressions.html
`,
	},
}
