// Code generated by cmd/all-keywords. DO NOT EDIT.

package lex

var KeywordsCategories = map[string]string{
	"abort":                     "U",
	"action":                    "U",
	"add":                       "U",
	"admin":                     "U",
	"aggregate":                 "U",
	"all":                       "R",
	"alter":                     "U",
	"analyse":                   "R",
	"analyze":                   "R",
	"and":                       "R",
	"annotate_type":             "C",
	"any":                       "R",
	"array":                     "R",
	"as":                        "R",
	"asc":                       "R",
	"asymmetric":                "R",
	"at":                        "U",
	"authorization":             "U",
	"automatic":                 "U",
	"backup":                    "U",
	"begin":                     "U",
	"between":                   "C",
	"bigint":                    "C",
	"bigserial":                 "U",
	"bit":                       "C",
	"blob":                      "U",
	"bool":                      "U",
	"boolean":                   "C",
	"both":                      "R",
	"bucket_count":              "U",
	"bundle":                    "U",
	"by":                        "U",
	"bytea":                     "U",
	"bytes":                     "U",
	"cache":                     "U",
	"cancel":                    "U",
	"cascade":                   "U",
	"case":                      "R",
	"cast":                      "R",
	"changefeed":                "U",
	"char":                      "C",
	"character":                 "C",
	"characteristics":           "C",
	"check":                     "R",
	"cluster":                   "U",
	"coalesce":                  "C",
	"collate":                   "R",
	"collation":                 "T",
	"column":                    "R",
	"columns":                   "U",
	"comment":                   "U",
	"commit":                    "U",
	"committed":                 "U",
	"compact":                   "U",
	"complete":                  "U",
	"concurrently":              "R",
	"configuration":             "U",
	"configurations":            "U",
	"configure":                 "U",
	"conflict":                  "U",
	"constraint":                "R",
	"constraints":               "U",
	"conversion":                "U",
	"copy":                      "U",
	"covering":                  "U",
	"create":                    "R",
	"createrole":                "U",
	"cross":                     "T",
	"cube":                      "U",
	"current":                   "U",
	"current_catalog":           "R",
	"current_date":              "R",
	"current_role":              "R",
	"current_schema":            "R",
	"current_time":              "R",
	"current_timestamp":         "R",
	"current_user":              "R",
	"cycle":                     "U",
	"data":                      "U",
	"database":                  "U",
	"databases":                 "U",
	"date":                      "U",
	"day":                       "U",
	"deallocate":                "U",
	"dec":                       "C",
	"decimal":                   "C",
	"default":                   "R",
	"deferrable":                "R",
	"deferred":                  "U",
	"delete":                    "U",
	"desc":                      "R",
	"discard":                   "U",
	"distinct":                  "R",
	"do":                        "R",
	"domain":                    "U",
	"double":                    "U",
	"drop":                      "U",
	"else":                      "R",
	"encoding":                  "U",
	"end":                       "R",
	"enum":                      "U",
	"escape":                    "U",
	"except":                    "R",
	"exclude":                   "U",
	"execute":                   "U",
	"exists":                    "C",
	"experimental":              "U",
	"experimental_audit":        "U",
	"experimental_fingerprints": "U",
	"experimental_relocate":     "U",
	"experimental_replica":      "U",
	"expiration":                "U",
	"explain":                   "U",
	"export":                    "U",
	"extension":                 "U",
	"extract":                   "C",
	"extract_duration":          "C",
	"false":                     "R",
	"family":                    "T",
	"fetch":                     "R",
	"files":                     "U",
	"filter":                    "U",
	"first":                     "U",
	"float":                     "C",
	"float4":                    "U",
	"float8":                    "U",
	"following":                 "U",
	"for":                       "R",
	"force_index":               "U",
	"foreign":                   "R",
	"from":                      "R",
	"full":                      "T",
	"function":                  "U",
	"global":                    "U",
	"grant":                     "R",
	"grants":                    "U",
	"greatest":                  "C",
	"group":                     "R",
	"grouping":                  "C",
	"groups":                    "U",
	"hash":                      "U",
	"having":                    "R",
	"high":                      "U",
	"histogram":                 "U",
	"hour":                      "U",
	"if":                        "C",
	"iferror":                   "C",
	"ifnull":                    "C",
	"ignore_foreign_keys":       "U",
	"ilike":                     "T",
	"immediate":                 "U",
	"import":                    "U",
	"in":                        "R",
	"include":                   "U",
	"increment":                 "U",
	"incremental":               "U",
	"index":                     "R",
	"indexes":                   "U",
	"inet":                      "U",
	"initially":                 "R",
	"inject":                    "U",
	"inner":                     "T",
	"insert":                    "U",
	"int":                       "C",
	"int2":                      "U",
	"int2vector":                "U",
	"int4":                      "U",
	"int64":                     "U",
	"int8":                      "U",
	"integer":                   "C",
	"interleave":                "U",
	"intersect":                 "R",
	"interval":                  "C",
	"into":                      "R",
	"inverted":                  "U",
	"is":                        "T",
	"iserror":                   "C",
	"isnull":                    "T",
	"isolation":                 "U",
	"job":                       "U",
	"jobs":                      "U",
	"join":                      "T",
	"json":                      "U",
	"jsonb":                     "U",
	"key":                       "U",
	"keys":                      "U",
	"kv":                        "U",
	"language":                  "U",
	"last":                      "U",
	"lateral":                   "R",
	"lc_collate":                "U",
	"lc_ctype":                  "U",
	"leading":                   "R",
	"lease":                     "U",
	"least":                     "C",
	"left":                      "T",
	"less":                      "U",
	"level":                     "U",
	"like":                      "T",
	"limit":                     "R",
	"list":                      "U",
	"local":                     "U",
	"localtime":                 "R",
	"localtimestamp":            "R",
	"locked":                    "U",
	"login":                     "U",
	"lookup":                    "U",
	"low":                       "U",
	"match":                     "U",
	"materialized":              "U",
	"maxvalue":                  "U",
	"merge":                     "U",
	"minute":                    "U",
	"minvalue":                  "U",
	"month":                     "U",
	"name":                      "U",
	"names":                     "U",
	"nan":                       "U",
	"natural":                   "T",
	"next":                      "U",
	"no":                        "U",
	"nocreaterole":              "U",
	"nologin":                   "U",
	"none":                      "T",
	"normal":                    "U",
	"not":                       "R",
	"nothing":                   "R",
	"notnull":                   "T",
	"nowait":                    "U",
	"no_index_join":             "U",
	"null":                      "R",
	"nullif":                    "C",
	"nulls":                     "U",
	"numeric":                   "C",
	"of":                        "U",
	"off":                       "U",
	"offset":                    "R",
	"oid":                       "U",
	"oids":                      "U",
	"oidvector":                 "U",
	"on":                        "R",
	"only":                      "R",
	"operator":                  "U",
	"opt":                       "U",
	"option":                    "U",
	"options":                   "U",
	"or":                        "R",
	"order":                     "R",
	"ordinality":                "U",
	"others":                    "U",
	"out":                       "C",
	"outer":                     "T",
	"over":                      "U",
	"overlaps":                  "T",
	"overlay":                   "C",
	"owned":                     "U",
	"parent":                    "U",
	"partial":                   "U",
	"partition":                 "U",
	"partitions":                "U",
	"password":                  "U",
	"pause":                     "U",
	"physical":                  "U",
	"placing":                   "R",
	"plan":                      "U",
	"plans":                     "U",
	"position":                  "C",
	"preceding":                 "U",
	"precision":                 "C",
	"prepare":                   "U",
	"preserve":                  "U",
	"primary":                   "R",
	"priority":                  "U",
	"public":                    "U",
	"publication":               "U",
	"queries":                   "U",
	"query":                     "U",
	"range":                     "U",
	"ranges":                    "U",
	"read":                      "U",
	"real":                      "C",
	"recursive":                 "U",
	"ref":                       "U",
	"references":                "R",
	"regclass":                  "U",
	"regnamespace":              "U",
	"regproc":                   "U",
	"regprocedure":              "U",
	"regtype":                   "U",
	"reindex":                   "U",
	"release":                   "U",
	"rename":                    "U",
	"repeatable":                "U",
	"replace":                   "U",
	"reset":                     "U",
	"restore":                   "U",
	"restrict":                  "U",
	"resume":                    "U",
	"returning":                 "R",
	"revoke":                    "U",
	"right":                     "T",
	"role":                      "U",
	"roles":                     "U",
	"rollback":                  "U",
	"rollup":                    "U",
	"row":                       "C",
	"rows":                      "U",
	"rule":                      "U",
	"savepoint":                 "U",
	"scatter":                   "U",
	"schema":                    "U",
	"schemas":                   "U",
	"scrub":                     "U",
	"search":                    "U",
	"second":                    "U",
	"select":                    "R",
	"sequence":                  "U",
	"sequences":                 "U",
	"serial":                    "U",
	"serial2":                   "U",
	"serial4":                   "U",
	"serial8":                   "U",
	"serializable":              "U",
	"server":                    "U",
	"session":                   "U",
	"sessions":                  "U",
	"session_user":              "R",
	"set":                       "U",
	"setting":                   "U",
	"settings":                  "U",
	"share":                     "U",
	"show":                      "U",
	"similar":                   "T",
	"simple":                    "U",
	"skip":                      "U",
	"smallint":                  "C",
	"smallserial":               "U",
	"snapshot":                  "U",
	"some":                      "R",
	"split":                     "U",
	"sql":                       "U",
	"start":                     "U",
	"statistics":                "U",
	"status":                    "U",
	"stdin":                     "U",
	"store":                     "U",
	"stored":                    "U",
	"storing":                   "U",
	"strict":                    "U",
	"string":                    "U",
	"subscription":              "U",
	"substring":                 "C",
	"symmetric":                 "R",
	"syntax":                    "U",
	"system":                    "U",
	"table":                     "R",
	"tables":                    "U",
	"temp":                      "U",
	"template":                  "U",
	"temporary":                 "U",
	"testing_relocate":          "U",
	"text":                      "U",
	"then":                      "R",
	"throttling":                "U",
	"ties":                      "U",
	"time":                      "C",
	"timestamp":                 "C",
	"timestamptz":               "C",
	"timetz":                    "C",
	"to":                        "R",
	"trace":                     "U",
	"trailing":                  "R",
	"transaction":               "U",
	"treat":                     "C",
	"trigger":                   "U",
	"trim":                      "C",
	"true":                      "R",
	"truncate":                  "U",
	"trusted":                   "U",
	"type":                      "U",
	"unbounded":                 "U",
	"uncommitted":               "U",
	"union":                     "R",
	"unique":                    "R",
	"unknown":                   "U",
	"unlogged":                  "U",
	"unsplit":                   "U",
	"until":                     "U",
	"update":                    "U",
	"upsert":                    "U",
	"use":                       "U",
	"user":                      "R",
	"users":                     "U",
	"using":                     "R",
	"uuid":                      "U",
	"valid":                     "U",
	"validate":                  "U",
	"value":                     "U",
	"values":                    "C",
	"varbit":                    "C",
	"varchar":                   "C",
	"variadic":                  "R",
	"varying":                   "U",
	"view":                      "U",
	"virtual":                   "C",
	"when":                      "R",
	"where":                     "R",
	"window":                    "R",
	"with":                      "R",
	"within":                    "U",
	"without":                   "U",
	"work":                      "C",
	"write":                     "U",
	"year":                      "U",
	"zone":                      "U",
}

// KeywordNames contains all keywords sorted, so that pg_get_keywords returns
// deterministic results.
var KeywordNames = []string{
	"abort",
	"action",
	"add",
	"admin",
	"aggregate",
	"all",
	"alter",
	"analyse",
	"analyze",
	"and",
	"annotate_type",
	"any",
	"array",
	"as",
	"asc",
	"asymmetric",
	"at",
	"authorization",
	"automatic",
	"backup",
	"begin",
	"between",
	"bigint",
	"bigserial",
	"bit",
	"blob",
	"bool",
	"boolean",
	"both",
	"bucket_count",
	"bundle",
	"by",
	"bytea",
	"bytes",
	"cache",
	"cancel",
	"cascade",
	"case",
	"cast",
	"changefeed",
	"char",
	"character",
	"characteristics",
	"check",
	"cluster",
	"coalesce",
	"collate",
	"collation",
	"column",
	"columns",
	"comment",
	"commit",
	"committed",
	"compact",
	"complete",
	"concurrently",
	"configuration",
	"configurations",
	"configure",
	"conflict",
	"constraint",
	"constraints",
	"conversion",
	"copy",
	"covering",
	"create",
	"createrole",
	"cross",
	"cube",
	"current",
	"current_catalog",
	"current_date",
	"current_role",
	"current_schema",
	"current_time",
	"current_timestamp",
	"current_user",
	"cycle",
	"data",
	"database",
	"databases",
	"date",
	"day",
	"deallocate",
	"dec",
	"decimal",
	"default",
	"deferrable",
	"deferred",
	"delete",
	"desc",
	"discard",
	"distinct",
	"do",
	"domain",
	"double",
	"drop",
	"else",
	"encoding",
	"end",
	"enum",
	"escape",
	"except",
	"exclude",
	"execute",
	"exists",
	"experimental",
	"experimental_audit",
	"experimental_fingerprints",
	"experimental_relocate",
	"experimental_replica",
	"expiration",
	"explain",
	"export",
	"extension",
	"extract",
	"extract_duration",
	"false",
	"family",
	"fetch",
	"files",
	"filter",
	"first",
	"float",
	"float4",
	"float8",
	"following",
	"for",
	"force_index",
	"foreign",
	"from",
	"full",
	"function",
	"global",
	"grant",
	"grants",
	"greatest",
	"group",
	"grouping",
	"groups",
	"hash",
	"having",
	"high",
	"histogram",
	"hour",
	"if",
	"iferror",
	"ifnull",
	"ignore_foreign_keys",
	"ilike",
	"immediate",
	"import",
	"in",
	"include",
	"increment",
	"incremental",
	"index",
	"indexes",
	"inet",
	"initially",
	"inject",
	"inner",
	"insert",
	"int",
	"int2",
	"int2vector",
	"int4",
	"int64",
	"int8",
	"integer",
	"interleave",
	"intersect",
	"interval",
	"into",
	"inverted",
	"is",
	"iserror",
	"isnull",
	"isolation",
	"job",
	"jobs",
	"join",
	"json",
	"jsonb",
	"key",
	"keys",
	"kv",
	"language",
	"last",
	"lateral",
	"lc_collate",
	"lc_ctype",
	"leading",
	"lease",
	"least",
	"left",
	"less",
	"level",
	"like",
	"limit",
	"list",
	"local",
	"localtime",
	"localtimestamp",
	"locked",
	"login",
	"lookup",
	"low",
	"match",
	"materialized",
	"maxvalue",
	"merge",
	"minute",
	"minvalue",
	"month",
	"name",
	"names",
	"nan",
	"natural",
	"next",
	"no",
	"nocreaterole",
	"nologin",
	"none",
	"normal",
	"not",
	"nothing",
	"notnull",
	"nowait",
	"no_index_join",
	"null",
	"nullif",
	"nulls",
	"numeric",
	"of",
	"off",
	"offset",
	"oid",
	"oids",
	"oidvector",
	"on",
	"only",
	"operator",
	"opt",
	"option",
	"options",
	"or",
	"order",
	"ordinality",
	"others",
	"out",
	"outer",
	"over",
	"overlaps",
	"overlay",
	"owned",
	"parent",
	"partial",
	"partition",
	"partitions",
	"password",
	"pause",
	"physical",
	"placing",
	"plan",
	"plans",
	"position",
	"preceding",
	"precision",
	"prepare",
	"preserve",
	"primary",
	"priority",
	"public",
	"publication",
	"queries",
	"query",
	"range",
	"ranges",
	"read",
	"real",
	"recursive",
	"ref",
	"references",
	"regclass",
	"regnamespace",
	"regproc",
	"regprocedure",
	"regtype",
	"reindex",
	"release",
	"rename",
	"repeatable",
	"replace",
	"reset",
	"restore",
	"restrict",
	"resume",
	"returning",
	"revoke",
	"right",
	"role",
	"roles",
	"rollback",
	"rollup",
	"row",
	"rows",
	"rule",
	"savepoint",
	"scatter",
	"schema",
	"schemas",
	"scrub",
	"search",
	"second",
	"select",
	"sequence",
	"sequences",
	"serial",
	"serial2",
	"serial4",
	"serial8",
	"serializable",
	"server",
	"session",
	"sessions",
	"session_user",
	"set",
	"setting",
	"settings",
	"share",
	"show",
	"similar",
	"simple",
	"skip",
	"smallint",
	"smallserial",
	"snapshot",
	"some",
	"split",
	"sql",
	"start",
	"statistics",
	"status",
	"stdin",
	"store",
	"stored",
	"storing",
	"strict",
	"string",
	"subscription",
	"substring",
	"symmetric",
	"syntax",
	"system",
	"table",
	"tables",
	"temp",
	"template",
	"temporary",
	"testing_relocate",
	"text",
	"then",
	"throttling",
	"ties",
	"time",
	"timestamp",
	"timestamptz",
	"timetz",
	"to",
	"trace",
	"trailing",
	"transaction",
	"treat",
	"trigger",
	"trim",
	"true",
	"truncate",
	"trusted",
	"type",
	"unbounded",
	"uncommitted",
	"union",
	"unique",
	"unknown",
	"unlogged",
	"unsplit",
	"until",
	"update",
	"upsert",
	"use",
	"user",
	"users",
	"using",
	"uuid",
	"valid",
	"validate",
	"value",
	"values",
	"varbit",
	"varchar",
	"variadic",
	"varying",
	"view",
	"virtual",
	"when",
	"where",
	"window",
	"with",
	"within",
	"without",
	"work",
	"write",
	"year",
	"zone",
}

// GetKeywordID returns the lex id of the SQL keyword k or IDENT if k is
// not a keyword.
func GetKeywordID(k string) int32 {
	// The previous implementation generated a map that did a string ->
	// id lookup. Various ideas were benchmarked and the implementation below
	// was the fastest of those, between 3% and 10% faster (at parsing, so the
	// scanning speedup is even more) than the map implementation.
	switch k {
	case "abort":
		return ABORT
	case "action":
		return ACTION
	case "add":
		return ADD
	case "admin":
		return ADMIN
	case "aggregate":
		return AGGREGATE
	case "all":
		return ALL
	case "alter":
		return ALTER
	case "analyse":
		return ANALYSE
	case "analyze":
		return ANALYZE
	case "and":
		return AND
	case "annotate_type":
		return ANNOTATE_TYPE
	case "any":
		return ANY
	case "array":
		return ARRAY
	case "as":
		return AS
	case "asc":
		return ASC
	case "asymmetric":
		return ASYMMETRIC
	case "at":
		return AT
	case "authorization":
		return AUTHORIZATION
	case "automatic":
		return AUTOMATIC
	case "backup":
		return BACKUP
	case "begin":
		return BEGIN
	case "between":
		return BETWEEN
	case "bigint":
		return BIGINT
	case "bigserial":
		return BIGSERIAL
	case "bit":
		return BIT
	case "blob":
		return BLOB
	case "bool":
		return BOOL
	case "boolean":
		return BOOLEAN
	case "both":
		return BOTH
	case "bucket_count":
		return BUCKET_COUNT
	case "bundle":
		return BUNDLE
	case "by":
		return BY
	case "bytea":
		return BYTEA
	case "bytes":
		return BYTES
	case "cache":
		return CACHE
	case "cancel":
		return CANCEL
	case "cascade":
		return CASCADE
	case "case":
		return CASE
	case "cast":
		return CAST
	case "changefeed":
		return CHANGEFEED
	case "char":
		return CHAR
	case "character":
		return CHARACTER
	case "characteristics":
		return CHARACTERISTICS
	case "check":
		return CHECK
	case "cluster":
		return CLUSTER
	case "coalesce":
		return COALESCE
	case "collate":
		return COLLATE
	case "collation":
		return COLLATION
	case "column":
		return COLUMN
	case "columns":
		return COLUMNS
	case "comment":
		return COMMENT
	case "commit":
		return COMMIT
	case "committed":
		return COMMITTED
	case "compact":
		return COMPACT
	case "complete":
		return COMPLETE
	case "concurrently":
		return CONCURRENTLY
	case "configuration":
		return CONFIGURATION
	case "configurations":
		return CONFIGURATIONS
	case "configure":
		return CONFIGURE
	case "conflict":
		return CONFLICT
	case "constraint":
		return CONSTRAINT
	case "constraints":
		return CONSTRAINTS
	case "conversion":
		return CONVERSION
	case "copy":
		return COPY
	case "covering":
		return COVERING
	case "create":
		return CREATE
	case "createrole":
		return CREATEROLE
	case "cross":
		return CROSS
	case "cube":
		return CUBE
	case "current":
		return CURRENT
	case "current_catalog":
		return CURRENT_CATALOG
	case "current_date":
		return CURRENT_DATE
	case "current_role":
		return CURRENT_ROLE
	case "current_schema":
		return CURRENT_SCHEMA
	case "current_time":
		return CURRENT_TIME
	case "current_timestamp":
		return CURRENT_TIMESTAMP
	case "current_user":
		return CURRENT_USER
	case "cycle":
		return CYCLE
	case "data":
		return DATA
	case "database":
		return DATABASE
	case "databases":
		return DATABASES
	case "date":
		return DATE
	case "day":
		return DAY
	case "deallocate":
		return DEALLOCATE
	case "dec":
		return DEC
	case "decimal":
		return DECIMAL
	case "default":
		return DEFAULT
	case "deferrable":
		return DEFERRABLE
	case "deferred":
		return DEFERRED
	case "delete":
		return DELETE
	case "desc":
		return DESC
	case "discard":
		return DISCARD
	case "distinct":
		return DISTINCT
	case "do":
		return DO
	case "domain":
		return DOMAIN
	case "double":
		return DOUBLE
	case "drop":
		return DROP
	case "else":
		return ELSE
	case "encoding":
		return ENCODING
	case "end":
		return END
	case "enum":
		return ENUM
	case "escape":
		return ESCAPE
	case "except":
		return EXCEPT
	case "exclude":
		return EXCLUDE
	case "execute":
		return EXECUTE
	case "exists":
		return EXISTS
	case "experimental":
		return EXPERIMENTAL
	case "experimental_audit":
		return EXPERIMENTAL_AUDIT
	case "experimental_fingerprints":
		return EXPERIMENTAL_FINGERPRINTS
	case "experimental_relocate":
		return EXPERIMENTAL_RELOCATE
	case "experimental_replica":
		return EXPERIMENTAL_REPLICA
	case "expiration":
		return EXPIRATION
	case "explain":
		return EXPLAIN
	case "export":
		return EXPORT
	case "extension":
		return EXTENSION
	case "extract":
		return EXTRACT
	case "extract_duration":
		return EXTRACT_DURATION
	case "false":
		return FALSE
	case "family":
		return FAMILY
	case "fetch":
		return FETCH
	case "files":
		return FILES
	case "filter":
		return FILTER
	case "first":
		return FIRST
	case "float":
		return FLOAT
	case "float4":
		return FLOAT4
	case "float8":
		return FLOAT8
	case "following":
		return FOLLOWING
	case "for":
		return FOR
	case "force_index":
		return FORCE_INDEX
	case "foreign":
		return FOREIGN
	case "from":
		return FROM
	case "full":
		return FULL
	case "function":
		return FUNCTION
	case "global":
		return GLOBAL
	case "grant":
		return GRANT
	case "grants":
		return GRANTS
	case "greatest":
		return GREATEST
	case "group":
		return GROUP
	case "grouping":
		return GROUPING
	case "groups":
		return GROUPS
	case "hash":
		return HASH
	case "having":
		return HAVING
	case "high":
		return HIGH
	case "histogram":
		return HISTOGRAM
	case "hour":
		return HOUR
	case "if":
		return IF
	case "iferror":
		return IFERROR
	case "ifnull":
		return IFNULL
	case "ignore_foreign_keys":
		return IGNORE_FOREIGN_KEYS
	case "ilike":
		return ILIKE
	case "immediate":
		return IMMEDIATE
	case "import":
		return IMPORT
	case "in":
		return IN
	case "include":
		return INCLUDE
	case "increment":
		return INCREMENT
	case "incremental":
		return INCREMENTAL
	case "index":
		return INDEX
	case "indexes":
		return INDEXES
	case "inet":
		return INET
	case "initially":
		return INITIALLY
	case "inject":
		return INJECT
	case "inner":
		return INNER
	case "insert":
		return INSERT
	case "int":
		return INT
	case "int2":
		return INT2
	case "int2vector":
		return INT2VECTOR
	case "int4":
		return INT4
	case "int64":
		return INT64
	case "int8":
		return INT8
	case "integer":
		return INTEGER
	case "interleave":
		return INTERLEAVE
	case "intersect":
		return INTERSECT
	case "interval":
		return INTERVAL
	case "into":
		return INTO
	case "inverted":
		return INVERTED
	case "is":
		return IS
	case "iserror":
		return ISERROR
	case "isnull":
		return ISNULL
	case "isolation":
		return ISOLATION
	case "job":
		return JOB
	case "jobs":
		return JOBS
	case "join":
		return JOIN
	case "json":
		return JSON
	case "jsonb":
		return JSONB
	case "key":
		return KEY
	case "keys":
		return KEYS
	case "kv":
		return KV
	case "language":
		return LANGUAGE
	case "last":
		return LAST
	case "lateral":
		return LATERAL
	case "lc_collate":
		return LC_COLLATE
	case "lc_ctype":
		return LC_CTYPE
	case "leading":
		return LEADING
	case "lease":
		return LEASE
	case "least":
		return LEAST
	case "left":
		return LEFT
	case "less":
		return LESS
	case "level":
		return LEVEL
	case "like":
		return LIKE
	case "limit":
		return LIMIT
	case "list":
		return LIST
	case "local":
		return LOCAL
	case "localtime":
		return LOCALTIME
	case "localtimestamp":
		return LOCALTIMESTAMP
	case "locked":
		return LOCKED
	case "login":
		return LOGIN
	case "lookup":
		return LOOKUP
	case "low":
		return LOW
	case "match":
		return MATCH
	case "materialized":
		return MATERIALIZED
	case "maxvalue":
		return MAXVALUE
	case "merge":
		return MERGE
	case "minute":
		return MINUTE
	case "minvalue":
		return MINVALUE
	case "month":
		return MONTH
	case "name":
		return NAME
	case "names":
		return NAMES
	case "nan":
		return NAN
	case "natural":
		return NATURAL
	case "next":
		return NEXT
	case "no":
		return NO
	case "nocreaterole":
		return NOCREATEROLE
	case "nologin":
		return NOLOGIN
	case "none":
		return NONE
	case "normal":
		return NORMAL
	case "not":
		return NOT
	case "nothing":
		return NOTHING
	case "notnull":
		return NOTNULL
	case "nowait":
		return NOWAIT
	case "no_index_join":
		return NO_INDEX_JOIN
	case "null":
		return NULL
	case "nullif":
		return NULLIF
	case "nulls":
		return NULLS
	case "numeric":
		return NUMERIC
	case "of":
		return OF
	case "off":
		return OFF
	case "offset":
		return OFFSET
	case "oid":
		return OID
	case "oids":
		return OIDS
	case "oidvector":
		return OIDVECTOR
	case "on":
		return ON
	case "only":
		return ONLY
	case "operator":
		return OPERATOR
	case "opt":
		return OPT
	case "option":
		return OPTION
	case "options":
		return OPTIONS
	case "or":
		return OR
	case "order":
		return ORDER
	case "ordinality":
		return ORDINALITY
	case "others":
		return OTHERS
	case "out":
		return OUT
	case "outer":
		return OUTER
	case "over":
		return OVER
	case "overlaps":
		return OVERLAPS
	case "overlay":
		return OVERLAY
	case "owned":
		return OWNED
	case "parent":
		return PARENT
	case "partial":
		return PARTIAL
	case "partition":
		return PARTITION
	case "partitions":
		return PARTITIONS
	case "password":
		return PASSWORD
	case "pause":
		return PAUSE
	case "physical":
		return PHYSICAL
	case "placing":
		return PLACING
	case "plan":
		return PLAN
	case "plans":
		return PLANS
	case "position":
		return POSITION
	case "preceding":
		return PRECEDING
	case "precision":
		return PRECISION
	case "prepare":
		return PREPARE
	case "preserve":
		return PRESERVE
	case "primary":
		return PRIMARY
	case "priority":
		return PRIORITY
	case "public":
		return PUBLIC
	case "publication":
		return PUBLICATION
	case "queries":
		return QUERIES
	case "query":
		return QUERY
	case "range":
		return RANGE
	case "ranges":
		return RANGES
	case "read":
		return READ
	case "real":
		return REAL
	case "recursive":
		return RECURSIVE
	case "ref":
		return REF
	case "references":
		return REFERENCES
	case "regclass":
		return REGCLASS
	case "regnamespace":
		return REGNAMESPACE
	case "regproc":
		return REGPROC
	case "regprocedure":
		return REGPROCEDURE
	case "regtype":
		return REGTYPE
	case "reindex":
		return REINDEX
	case "release":
		return RELEASE
	case "rename":
		return RENAME
	case "repeatable":
		return REPEATABLE
	case "replace":
		return REPLACE
	case "reset":
		return RESET
	case "restore":
		return RESTORE
	case "restrict":
		return RESTRICT
	case "resume":
		return RESUME
	case "returning":
		return RETURNING
	case "revoke":
		return REVOKE
	case "right":
		return RIGHT
	case "role":
		return ROLE
	case "roles":
		return ROLES
	case "rollback":
		return ROLLBACK
	case "rollup":
		return ROLLUP
	case "row":
		return ROW
	case "rows":
		return ROWS
	case "rule":
		return RULE
	case "savepoint":
		return SAVEPOINT
	case "scatter":
		return SCATTER
	case "schema":
		return SCHEMA
	case "schemas":
		return SCHEMAS
	case "scrub":
		return SCRUB
	case "search":
		return SEARCH
	case "second":
		return SECOND
	case "select":
		return SELECT
	case "sequence":
		return SEQUENCE
	case "sequences":
		return SEQUENCES
	case "serial":
		return SERIAL
	case "serial2":
		return SERIAL2
	case "serial4":
		return SERIAL4
	case "serial8":
		return SERIAL8
	case "serializable":
		return SERIALIZABLE
	case "server":
		return SERVER
	case "session":
		return SESSION
	case "sessions":
		return SESSIONS
	case "session_user":
		return SESSION_USER
	case "set":
		return SET
	case "setting":
		return SETTING
	case "settings":
		return SETTINGS
	case "share":
		return SHARE
	case "show":
		return SHOW
	case "similar":
		return SIMILAR
	case "simple":
		return SIMPLE
	case "skip":
		return SKIP
	case "smallint":
		return SMALLINT
	case "smallserial":
		return SMALLSERIAL
	case "snapshot":
		return SNAPSHOT
	case "some":
		return SOME
	case "split":
		return SPLIT
	case "sql":
		return SQL
	case "start":
		return START
	case "statistics":
		return STATISTICS
	case "status":
		return STATUS
	case "stdin":
		return STDIN
	case "store":
		return STORE
	case "stored":
		return STORED
	case "storing":
		return STORING
	case "strict":
		return STRICT
	case "string":
		return STRING
	case "subscription":
		return SUBSCRIPTION
	case "substring":
		return SUBSTRING
	case "symmetric":
		return SYMMETRIC
	case "syntax":
		return SYNTAX
	case "system":
		return SYSTEM
	case "table":
		return TABLE
	case "tables":
		return TABLES
	case "temp":
		return TEMP
	case "template":
		return TEMPLATE
	case "temporary":
		return TEMPORARY
	case "testing_relocate":
		return TESTING_RELOCATE
	case "text":
		return TEXT
	case "then":
		return THEN
	case "throttling":
		return THROTTLING
	case "ties":
		return TIES
	case "time":
		return TIME
	case "timestamp":
		return TIMESTAMP
	case "timestamptz":
		return TIMESTAMPTZ
	case "timetz":
		return TIMETZ
	case "to":
		return TO
	case "trace":
		return TRACE
	case "trailing":
		return TRAILING
	case "transaction":
		return TRANSACTION
	case "treat":
		return TREAT
	case "trigger":
		return TRIGGER
	case "trim":
		return TRIM
	case "true":
		return TRUE
	case "truncate":
		return TRUNCATE
	case "trusted":
		return TRUSTED
	case "type":
		return TYPE
	case "unbounded":
		return UNBOUNDED
	case "uncommitted":
		return UNCOMMITTED
	case "union":
		return UNION
	case "unique":
		return UNIQUE
	case "unknown":
		return UNKNOWN
	case "unlogged":
		return UNLOGGED
	case "unsplit":
		return UNSPLIT
	case "until":
		return UNTIL
	case "update":
		return UPDATE
	case "upsert":
		return UPSERT
	case "use":
		return USE
	case "user":
		return USER
	case "users":
		return USERS
	case "using":
		return USING
	case "uuid":
		return UUID
	case "valid":
		return VALID
	case "validate":
		return VALIDATE
	case "value":
		return VALUE
	case "values":
		return VALUES
	case "varbit":
		return VARBIT
	case "varchar":
		return VARCHAR
	case "variadic":
		return VARIADIC
	case "varying":
		return VARYING
	case "view":
		return VIEW
	case "virtual":
		return VIRTUAL
	case "when":
		return WHEN
	case "where":
		return WHERE
	case "window":
		return WINDOW
	case "with":
		return WITH
	case "within":
		return WITHIN
	case "without":
		return WITHOUT
	case "work":
		return WORK
	case "write":
		return WRITE
	case "year":
		return YEAR
	case "zone":
		return ZONE
	default:
		return IDENT
	}
}
